version: "3"
services:
  app:
    container_name: ${CON_NAME}
    hostname: ${HOST_NAME}
    image: ${IMAGE}:${VERSION}
    # networks:
    #   - app_net
    restart: always
    ports:
      - ${PORT_OUT}:${PORT_IN}
    command:
      - /bin/sh
      - -c
      - |
        npm i -g green-tunnel
        npm i -g npm@
        npm i -g npm-check-updates
        gt --ip 0.0.0.0 --port ${PORT_IN} --system-proxy true

# networks:
#   app_net:
#     external:
#       name: ${NET_APP}